name: CI pipeline

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      ERE_DIRECTORY_WATCHER_DIR: watch-pdf
      ERE_CONNECTOR_TLS_CERT_TRUST_STORE_FILE: ${{ github.workspace }}\\src\\test\\resources\\certs\\ps_erp_incentergy_01.p12
      ERE_CONNECTOR_TLS_CERT_TRUST_STORE_PWD: "00"
      ERE_VALIDATOR_VALIDATE_SIGN_REQUEST_BUNDLES_ENABLED: no

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B verify
      - name: Spotbugs
        run: mvn -B verify spotbugs:spotbugs
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
      - name: PMD
        run: mvn -B verify pmd:pmd
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'
